### ISSUE TITLE
.removeEmojis() is not working with newer emojis from the last ios update

### ISSUE THREAD

**Issue by ServusJon** [onmyway133/Smile#3]

**Comment by onmyway133** [comment]
@ServusJon Hi, you mean these emojis http://time.com/4598255/apple-ios-release-update-emoji/ ?

**Comment by ServusJon** [comment]
Yes 😊

**Comment by ServusJon** [comment]
Could you please add those to Smile? Would mean a lot to me!

**Comment by onmyway133** [comment]
@ServusJon Hi, I will take a look

**Comment by onmyway133** [comment]
@ServusJon Hi, I updated the tests https://github.com/onmyway133/Smile/commit/c387945e32d03875db662668a751e61f8b76e3a1 according to http://blog.emojipedia.org/ios-10-2-emoji-changelog/

Can you give me a test that fails?

**Comment by ServusJon** [comment]
thanks @onmyway133 but sadly a lot emoji weren't caught like that one: 🤑

Also the .removeEmojis function fails when there are emojis with different skin color.

**Comment by onmyway133** [comment]
@ServusJon Hi, this 🤑 works. But `removeEmojis` does not handle emoji with skin tone. I just fixed it for you https://github.com/onmyway133/Smile/commit/7a92029ff085ee0283a9257bb0ebc653db01fb8d

**Comment by ServusJon** [comment]
Don't really have a list but these seem get through. Some also with a gender symbol. I didn't test every emoji but I did some stress testing. Thank you so much for your effort!

<img width="706" alt="bildschirmfoto 2017-05-13 um 20 39 20" src="https://cloud.githubusercontent.com/assets/783416/26028216/4788ad0e-381c-11e7-952e-a06818e5963b.png">

**Comment by onmyway133** [comment]
@ServusJon yeah, glad that it works for you 🎉  I will close this PR for now. Feel free to ping me if you have any ideas on improvement 😉

**Comment by ServusJon** [comment]
@onmyway133 these emojis that you see aren't affected by Smile. Could you please add them as well? Thank you!

**Comment by onmyway133** [comment]
@ServusJon yeah, I will check for that

**Comment by onmyway133** [comment]
@ServusJon Hi, I fixed it for you, you can checkout latest version on master. Note that you should use `iOS` or `Chrome` emojis, not `macOS` emojis. They are different

**Comment by onmyway133** [comment]
@ServusJon Hi, I updated 1.1.1 https://github.com/onmyway133/Smile/releases/tag/1.1.1 which may fix your issues

**Comment by ServusJon** [comment]
Works like a charm! Thank you!

**Comment by onmyway133** [comment]
Glad that it helps 🚀
