### ISSUE TITLE
Smile.containsEmoji thinks Digits are emojis

### ISSUE THREAD

**Issue by ServusJon** [onmyway133/Smile#4]
Seems like the Smile.containsEmoji function thinks Digits are emojis. Could you please fix that? :-)

**Comment by onmyway133** [comment]
@ServusJon Hi, you mean digit `3` or `:three:`?

**Comment by ServusJon** [comment]
3. Any number really

**Comment by onmyway133** [comment]
@ServusJon Hi, sorry for late response. I 've been busy recently, so I will try to fix it when possible.

**Comment by ServusJon** [comment]
Yes. Thar would be awesome!

**Comment by ServusJon** [comment]
@onmyway133 It would be so awesome if you can fix that :-)

**Comment by onmyway133** [comment]
@ServusJon Hi, please check https://github.com/onmyway133/Smile/releases/tag/1.3.0, let me know if it helps 😉

**Comment by ServusJon** [comment]
Thank you!!!
