### ISSUE TITLE
Question: What's required to update Smile to include latest iOS 11.1 emoji (vampire, mermaid, etc)?

### ISSUE THREAD

**Issue by kharmabum** [onmyway133/Smile#5]
See: https://blog.emojipedia.org/ios-11-1-emoji-changelog/

**Comment by kharmabum** [comment]
@onmyway133 I went ahead and compiled a list of the new emoji with associated code points and aliases (I did my best to match the conventions already in Smile). https://gist.github.com/kharmabum/0dc6307a0bbccb8a76f93973db00abce

**Comment by Francescu** [comment]
@kharmabum does my PR #6 fixed the issue?

**Comment by kharmabum** [comment]
@Francescu I would say it's mostly sufficient. The lack of gendered versions of a few of the emoji is regrettable, but you may have had a compelling reason to leave those out.

**Comment by Francescu** [comment]
I’m not aware of those. Could you list which variations are not working so I can try to fix?

Francescu

**Comment by kharmabum** [comment]
🙏👍

- JC
________________________________

**Comment by onmyway133** [comment]
@Francescu @kharmabum Thanks for your contribution ❤️ If you 'd like to be make more changes, I 'd be very happy to add you as contributors to the project
